# Generated by Django 5.2 on 2025-07-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('PLANETA', 'Planeta'), ('ESTRELA', 'Estrela'), ('GALÁXIA', 'Galáxia'), ('NEBULOSA', 'Nebulosa')], default='', max_length=100),
        ),
    ]
